pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: "Build"
    jobs:
      - job: DotNetCoreBuild
        steps:
        - script: 'npm install -g --production windows-build-tools --vs2015'
        - script: 'npm --loglevel=error install .\\src\\PartsUnlimitedWebsite\\'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.csproj'