pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: "Build"
    jobs:
      - job: DotNetCoreBuild
        steps:
        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: 'src/PartsUnlimitedWebsite'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.csproj'