trigger: none

pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solutionName: 'PartsUnlimited.sln'
  webSitePath: 'src\PartsUnlimitedWebSite\PartsUnlimitedWebsite.csproj'
  testPath: 'test\PartsUnlimited.UnitTests\PartsUnlimited.UnitTests.csproj'

stages:
  - stage: "Build"
    jobs:
      - job: DotNetCoreBuild
        steps:
          - script: 'dotnet restore $(solutionName)'
            displayName: 'dotnet restore'
          - script: 'dotnet build  $(System.DefaultWorkingDirectory)\$(webSite) --configuration $(buildConfiguration) --verbosity d'
            displayName: 'dotnet build website'
          - script: 'dotnet build  $(System.DefaultWorkingDirectory)\$(testPath) --configuration $(buildConfiguration) --verbosity d'
            displayName: 'dotnet build tests'
